[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; LDF가 불필요한 깊이까지 탐색하지 않도록 제한
lib_ldf_mode = chain

; 다른 보드용 통신 라이브러리 강제 컴파일 차단
lib_ignore =
  WiFi101
  WiFi101_Generic
  WiFiEspAT
  STM32Ethernet
  Ethernet
  WiFiNINA_Generic
  ESP8266_AT_WebServer
  UIPEthernet

; 명시적으로 필요한 라이브러리만 설치
lib_deps =
  khoih-prog/MySQL_MariaDB_Generic @ ^1.7.2
  bblanchon/ArduinoJson @ ^7.4.3