[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit SHT4x Library @ ^1.0.4
  claws/BH1750 @ ^1.3.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/Adafruit BusIO
